# Generated by Django 4.2 on 2024-02-21 12:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("financial", "0005_alter_payment_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="user",
        ),
    ]
