# Generated by Django 4.2 on 2024-02-20 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 20, 13, 17, 14, 383608, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Published",
            ),
        ),
    ]
