# Generated by Django 4.2 on 2024-02-20 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_post_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 20, 14, 47, 30, 880947, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Published",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="thumbnail",
            field=models.ImageField(
                default="no-image.jpg",
                null=True,
                upload_to="",
                verbose_name="Thumbnail",
            ),
        ),
    ]
