# Generated by Django 4.2 on 2024-02-21 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_post_published_alter_post_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 21, 6, 7, 26, 706615, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Published",
            ),
        ),
    ]
