# Generated by Django 4.2 on 2024-02-21 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_alter_category_slug_alter_post_published_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 21, 7, 19, 2, 548866, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Published",
            ),
        ),
    ]
