# Generated by Django 4.2 on 2024-02-21 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_alter_post_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 21, 7, 20, 52, 903740, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Published",
            ),
        ),
    ]
