# Generated by Django 4.2 on 2024-02-21 07:35

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0012_alter_post_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("-created_at",)},
        ),
        migrations.RemoveField(
            model_name="post",
            name="published",
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                blank=True,
                default=None,
                editable=False,
                max_length=250,
                null=True,
                populate_from="title",
                unique=True,
            ),
        ),
    ]
