# Generated by Django 4.2 on 2024-02-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0013_alter_post_options_remove_post_published_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="post",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                default="no-image.jpg",
                null=True,
                upload_to="",
                verbose_name="Thumbnail",
            ),
        ),
    ]
