# Generated by Django 4.2 on 2024-02-25 19:02

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0015_alter_category_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gallery",
            name="image",
        ),
        migrations.RemoveField(
            model_name="gallery",
            name="video",
        ),
        migrations.AddField(
            model_name="gallery",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gallery",
            name="media",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                null=True, verbose_name="image_or_video"
            ),
        ),
    ]
