# Generated by Django 4.2 on 2024-02-26 06:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0016_remove_gallery_image_remove_gallery_video_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
