# Generated by Django 4.2 on 2024-03-06 16:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0017_alter_comment_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=ckeditor.fields.RichTextField(verbose_name="Title"),
        ),
    ]
