# Generated by Django 4.2 on 2024-02-21 07:11

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_alter_shopcategory_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopcategory",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                blank=True,
                editable=True,
                max_length=250,
                null=True,
                populate_from="name",
            ),
        ),
    ]
