# Generated by Django 4.2 on 2024-02-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_alter_shopcategory_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                default="no-image.jpg",
                null=True,
                upload_to="",
                verbose_name="product_thumbnail",
            ),
        ),
        migrations.AlterField(
            model_name="shopgallery",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="shopgallery",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
