# Generated by Django 4.2 on 2024-02-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_alter_product_thumbnail_alter_shopgallery_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.ManyToManyField(related_name="product", to="shop.price"),
        ),
    ]
