# Generated by Django 4.2 on 2024-02-25 19:02

import autoslug.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0007_remove_product_price_product_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shopgallery",
            name="image",
        ),
        migrations.RemoveField(
            model_name="shopgallery",
            name="video",
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                blank=True,
                default=None,
                editable=False,
                max_length=250,
                null=True,
                populate_from="name",
                unique_for_date="created_at",
            ),
        ),
        migrations.AddField(
            model_name="shopgallery",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shopgallery",
            name="media",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                null=True, verbose_name="image_or_video"
            ),
        ),
    ]
