# Generated by Django 4.2 on 2024-02-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_remove_cartitem_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="total_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Total_price",
            ),
        ),
    ]
